<?php

// This file was generated by running "composer dump-env prod"

// return array (
//   'APP_ENV' => 'prod',
//   'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
//   'APP_SECRET' => '4680bd22da38bb15b177fce20114140f',
//   'DATABASE_URL' => 'mysql://id19992334_miguel:@tT3ZVA%x!>)=8o}@127.0.0.1:3306/id19992334_tfc',
// );
