<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_DEBUG'=> 0,
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
  'APP_SECRET' => '4680bd22da38bb15b177fce20114140f',
  'DATABASE_URL' => 'mysql://root:@127.0.0.1:3306/tfc?serverVersion=10.4.24-MariaDB&charset=utf8mb4',
);
