<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
  'APP_SECRET' => '4680bd22da38bb15b177fce20114140f',
  'DATABASE_URL' => 'mysql://rdcussdegc:dRm2aWPxtG@127.0.0.1:3306/rdcussdegc?serverVersion=10.4.20-MariaDB&charset=utf8',
);
