<?php

namespace ContainerYSLTbli;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9CfOQS0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9CfOQS0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9CfOQS0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CitaController::createAction' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\CitaController::deleteAction' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\CitaController::indexAction' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\CitaController::updateAction' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\FamiliaController::anular' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\FamiliaController::anular_cita' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\FamiliaController::consultasOrientacion' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\FamiliaController::consultasSecretaria' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\FamiliaController::consultasTutoria' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\FamiliaController::indexOrientacion' => ['privates', '.service_locator.PbFLIDh', 'get_ServiceLocator_PbFLIDhService', true],
            'App\\Controller\\FamiliaController::indexSecretaria' => ['privates', '.service_locator.PbFLIDh', 'get_ServiceLocator_PbFLIDhService', true],
            'App\\Controller\\FamiliaController::indexTutoria' => ['privates', '.service_locator.PbFLIDh', 'get_ServiceLocator_PbFLIDhService', true],
            'App\\Controller\\FamiliaController::listado' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\FamiliaController::menuFamilias' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\FamiliaController::reserva' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\FamiliaController::reservaTutoria' => ['privates', '.service_locator.PbFLIDh', 'get_ServiceLocator_PbFLIDhService', true],
            'App\\Controller\\LoginController::index' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.YU8H6ve', 'get_ServiceLocator_YU8H6veService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\CitaController:createAction' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\CitaController:deleteAction' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\CitaController:indexAction' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\CitaController:updateAction' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\FamiliaController:anular' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\FamiliaController:anular_cita' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\FamiliaController:consultasOrientacion' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\FamiliaController:consultasSecretaria' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\FamiliaController:consultasTutoria' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\FamiliaController:indexOrientacion' => ['privates', '.service_locator.PbFLIDh', 'get_ServiceLocator_PbFLIDhService', true],
            'App\\Controller\\FamiliaController:indexSecretaria' => ['privates', '.service_locator.PbFLIDh', 'get_ServiceLocator_PbFLIDhService', true],
            'App\\Controller\\FamiliaController:indexTutoria' => ['privates', '.service_locator.PbFLIDh', 'get_ServiceLocator_PbFLIDhService', true],
            'App\\Controller\\FamiliaController:listado' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\FamiliaController:menuFamilias' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\FamiliaController:reserva' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\FamiliaController:reservaTutoria' => ['privates', '.service_locator.PbFLIDh', 'get_ServiceLocator_PbFLIDhService', true],
            'App\\Controller\\LoginController:index' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.YU8H6ve', 'get_ServiceLocator_YU8H6veService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\CitaController::createAction' => '?',
            'App\\Controller\\CitaController::deleteAction' => '?',
            'App\\Controller\\CitaController::indexAction' => '?',
            'App\\Controller\\CitaController::updateAction' => '?',
            'App\\Controller\\FamiliaController::anular' => '?',
            'App\\Controller\\FamiliaController::anular_cita' => '?',
            'App\\Controller\\FamiliaController::consultasOrientacion' => '?',
            'App\\Controller\\FamiliaController::consultasSecretaria' => '?',
            'App\\Controller\\FamiliaController::consultasTutoria' => '?',
            'App\\Controller\\FamiliaController::indexOrientacion' => '?',
            'App\\Controller\\FamiliaController::indexSecretaria' => '?',
            'App\\Controller\\FamiliaController::indexTutoria' => '?',
            'App\\Controller\\FamiliaController::listado' => '?',
            'App\\Controller\\FamiliaController::menuFamilias' => '?',
            'App\\Controller\\FamiliaController::reserva' => '?',
            'App\\Controller\\FamiliaController::reservaTutoria' => '?',
            'App\\Controller\\LoginController::index' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\CitaController:createAction' => '?',
            'App\\Controller\\CitaController:deleteAction' => '?',
            'App\\Controller\\CitaController:indexAction' => '?',
            'App\\Controller\\CitaController:updateAction' => '?',
            'App\\Controller\\FamiliaController:anular' => '?',
            'App\\Controller\\FamiliaController:anular_cita' => '?',
            'App\\Controller\\FamiliaController:consultasOrientacion' => '?',
            'App\\Controller\\FamiliaController:consultasSecretaria' => '?',
            'App\\Controller\\FamiliaController:consultasTutoria' => '?',
            'App\\Controller\\FamiliaController:indexOrientacion' => '?',
            'App\\Controller\\FamiliaController:indexSecretaria' => '?',
            'App\\Controller\\FamiliaController:indexTutoria' => '?',
            'App\\Controller\\FamiliaController:listado' => '?',
            'App\\Controller\\FamiliaController:menuFamilias' => '?',
            'App\\Controller\\FamiliaController:reserva' => '?',
            'App\\Controller\\FamiliaController:reservaTutoria' => '?',
            'App\\Controller\\LoginController:index' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
