<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVtlaZgD\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVtlaZgD/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerVtlaZgD.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerVtlaZgD\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerVtlaZgD\App_KernelProdContainer([
    'container.build_hash' => 'VtlaZgD',
    'container.build_id' => '3b7f0f5c',
    'container.build_time' => 1671381714,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVtlaZgD');
