<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDydCUiE\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDydCUiE/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerDydCUiE.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerDydCUiE\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerDydCUiE\App_KernelProdContainer([
    'container.build_hash' => 'DydCUiE',
    'container.build_id' => '49974812',
    'container.build_time' => 1671368446,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDydCUiE');
