<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'api_event_edit' => [['id'], ['_controller' => 'App\\Controller\\ApiController::majEvent'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/api']], [], [], []],
    'app_calendar_index' => [[], ['_controller' => 'App\\Controller\\CalendarController::index'], [], [['text', '/calendar/']], [], [], []],
    'app_calendar_new' => [[], ['_controller' => 'App\\Controller\\CalendarController::new'], [], [['text', '/calendar/new']], [], [], []],
    'app_calendar_show' => [['id'], ['_controller' => 'App\\Controller\\CalendarController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/calendar']], [], [], []],
    'app_calendar_edit' => [['id'], ['_controller' => 'App\\Controller\\CalendarController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/calendar']], [], [], []],
    'app_calendar_delete' => [['id'], ['_controller' => 'App\\Controller\\CalendarController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/calendar']], [], [], []],
    'anular' => [['id'], ['_controller' => 'App\\Controller\\FamiliaController::anular'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/anular']], [], [], []],
    'showTutores' => [[], ['_controller' => 'App\\Controller\\FamiliaController::listadoTutoria'], [], [['text', '/familia/tutor']], [], [], []],
    'tutoria' => [[], ['_controller' => 'App\\Controller\\FamiliaController::indexTutoria'], [], [['text', '/familia/tutor/Tutoría']], [], [], []],
    'tutoria_reserva' => [['id'], ['_controller' => 'App\\Controller\\FamiliaController::reservaTutoria'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/familia/tutor/Tutoría']], [], [], []],
    'cita_consulta_tutoria' => [['username'], ['_controller' => 'App\\Controller\\FamiliaController::consultasTutoria'], [], [['variable', '/', '[^/]++', 'username', true], ['text', '/familia/tutor/Tutoría/consulta']], [], [], []],
    'showOrientacion' => [[], ['_controller' => 'App\\Controller\\FamiliaController::listadoOrientacion'], [], [['text', '/familia/orientador']], [], [], []],
    'orientacion' => [[], ['_controller' => 'App\\Controller\\FamiliaController::indexOrientacion'], [], [['text', '/familia/orientador/Orientación']], [], [], []],
    'orientación_reserva' => [['id'], ['_controller' => 'App\\Controller\\FamiliaController::reservaOrientación'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/familia/orientador/Orientación']], [], [], []],
    'consulta_orientación' => [['username'], ['_controller' => 'App\\Controller\\FamiliaController::consultasOrientación'], [], [['variable', '/', '[^/]++', 'username', true], ['text', '/familia/orientador/Orientación/consulta']], [], [], []],
    'showSecretaria' => [[], ['_controller' => 'App\\Controller\\FamiliaController::listadoSecretaria'], [], [['text', '/familia/secretario']], [], [], []],
    'secretaria' => [[], ['_controller' => 'App\\Controller\\FamiliaController::indexSecretaria'], [], [['text', '/familia/secretario/Secretaría']], [], [], []],
    'secretaria_reserva' => [['id'], ['_controller' => 'App\\Controller\\FamiliaController::reservaSecretaria'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/familia/secretario/Secretaría']], [], [], []],
    'cita_consulta_secretaria' => [['username'], ['_controller' => 'App\\Controller\\FamiliaController::consultasSecretaria'], [], [['variable', '/', '[^/]++', 'username', true], ['text', '/familia/secretario/Secretaría/consulta']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\LoginController::index'], [], [['text', '/login']], [], [], []],
    'main' => [[], ['_controller' => 'App\\Controller\\MainController::index'], [], [['text', '/']], [], [], []],
    'plantilla' => [[], ['_controller' => 'App\\Controller\\MainController::indexPlantilla'], [], [['text', '/plantilla']], [], [], []],
    'familia' => [[], ['_controller' => 'App\\Controller\\MainController::indexFamilia'], [], [['text', '/familia']], [], [], []],
    'aniadir_citas' => [[], ['_controller' => 'App\\Controller\\PlantillaController::addCitas'], [], [['text', '/añadir_citas']], [], [], []],
    'misCitas' => [[], ['_controller' => 'App\\Controller\\PlantillaController::misCitas'], [], [['text', '/miscitas']], [], [], []],
    'addUser' => [[], ['_controller' => 'App\\Controller\\PlantillaController::addAdminUser'], [], [['text', '/addUser']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], [], []],
    'app_logout' => [[], [], [], [['text', '/logout']], [], [], []],
];
