<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_login' => [[], ['_controller' => 'App\\Controller\\LoginController::index'], [], [['text', '/login']], [], [], []],
    'main' => [[], ['_controller' => 'App\\Controller\\MainController::index'], [], [['text', '/']], [], [], []],
    'alumnado' => [[], ['_controller' => 'App\\Controller\\MainController::indexAlumnado'], [], [['text', '/alumnado']], [], [], []],
    'plantilla' => [[], ['_controller' => 'App\\Controller\\MainController::indexPlantilla'], [], [['text', '/plantilla']], [], [], []],
    'tutor' => [[], ['_controller' => 'App\\Controller\\MainController::indexTutor'], [], [['text', '/tutor']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], [], []],
    'app_tutoria' => [[], ['_controller' => 'App\\Controller\\TutoriaController::index'], [], [['text', '/tutoria']], [], [], []],
    'app_logout' => [[], [], [], [['text', '/logout']], [], [], []],
];
