<?php

namespace ContainerMlCJ9Bp;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_955E_CyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.955E.cy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.955E.cy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'authenticationUtils' => ['privates', 'security.authentication_utils', 'getSecurity_AuthenticationUtilsService', true],
            'calendar' => ['privates', 'App\\Repository\\CalendarRepository', 'getCalendarRepositoryService', true],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'authenticationUtils' => '?',
            'calendar' => 'App\\Repository\\CalendarRepository',
            'doctrine' => '?',
        ]);
    }
}
