<?php

namespace ContainerDMKZhB4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrientacionRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\OrientacionRepository' shared autowired service.
     *
     * @return \App\Repository\OrientacionRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\OrientacionRepository'] = new \App\Repository\OrientacionRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
