<?php

namespace ContainerHjwniMu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTutorTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\TutorType' shared autowired service.
     *
     * @return \App\Form\TutorType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\TutorType'] = new \App\Form\TutorType();
    }
}
