<?php

namespace ContainerHjwniMu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTutorRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\TutorRepository' shared autowired service.
     *
     * @return \App\Repository\TutorRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\TutorRepository'] = new \App\Repository\TutorRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
