<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSGIh1t8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSGIh1t8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSGIh1t8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSGIh1t8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSGIh1t8\App_KernelDevDebugContainer([
    'container.build_hash' => 'SGIh1t8',
    'container.build_id' => '862f0c1f',
    'container.build_time' => 1660810332,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSGIh1t8');
