<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8NBHSku\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8NBHSku/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8NBHSku.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8NBHSku\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8NBHSku\App_KernelDevDebugContainer([
    'container.build_hash' => '8NBHSku',
    'container.build_id' => '74bb9984',
    'container.build_time' => 1670920180,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8NBHSku');
