<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerB5k6pYT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerB5k6pYT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerB5k6pYT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerB5k6pYT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerB5k6pYT\App_KernelDevDebugContainer([
    'container.build_hash' => 'B5k6pYT',
    'container.build_id' => 'd6c8b6ab',
    'container.build_time' => 1659082081,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerB5k6pYT');
