<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Tutor extends \App\Entity\Tutor implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Tutor' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Tutor' . "\0" . 'user', '' . "\0" . 'App\\Entity\\Tutor' . "\0" . 'reserva', '' . "\0" . 'App\\Entity\\Tutor' . "\0" . 'username', '' . "\0" . 'App\\Entity\\Tutor' . "\0" . 'calendars', '' . "\0" . 'App\\Entity\\Tutor' . "\0" . 'servicios'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Tutor' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Tutor' . "\0" . 'user', '' . "\0" . 'App\\Entity\\Tutor' . "\0" . 'reserva', '' . "\0" . 'App\\Entity\\Tutor' . "\0" . 'username', '' . "\0" . 'App\\Entity\\Tutor' . "\0" . 'calendars', '' . "\0" . 'App\\Entity\\Tutor' . "\0" . 'servicios'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Tutor $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getUser(): ?\App\Entity\user
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(?\App\Entity\user $user): \App\Entity\Tutor
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getReserva(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReserva', []);

        return parent::getReserva();
    }

    /**
     * {@inheritDoc}
     */
    public function addReserva(\App\Entity\Reserva $reserva): \App\Entity\Tutor
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addReserva', [$reserva]);

        return parent::addReserva($reserva);
    }

    /**
     * {@inheritDoc}
     */
    public function removeReserva(\App\Entity\Reserva $reserva): \App\Entity\Tutor
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeReserva', [$reserva]);

        return parent::removeReserva($reserva);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', []);

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsername(?string $username): \App\Entity\Tutor
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsername', [$username]);

        return parent::setUsername($username);
    }

    /**
     * {@inheritDoc}
     */
    public function getCalendars(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCalendars', []);

        return parent::getCalendars();
    }

    /**
     * {@inheritDoc}
     */
    public function addCalendar(\App\Entity\Calendar $calendar): \App\Entity\Tutor
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCalendar', [$calendar]);

        return parent::addCalendar($calendar);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCalendar(\App\Entity\Calendar $calendar): \App\Entity\Tutor
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCalendar', [$calendar]);

        return parent::removeCalendar($calendar);
    }

    /**
     * {@inheritDoc}
     */
    public function getServicios(): ?\App\Entity\Servicios
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getServicios', []);

        return parent::getServicios();
    }

    /**
     * {@inheritDoc}
     */
    public function setServicios(?\App\Entity\Servicios $servicios): \App\Entity\Tutor
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setServicios', [$servicios]);

        return parent::setServicios($servicios);
    }

}
